/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ResultRouteImport } from './routes/result'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiIndexRouteImport } from './routes/ai.index'
import { Route as PackageIdRouteImport } from './routes/package.$id'
import { Route as HotelIdRouteImport } from './routes/hotel.$id'
import { Route as FlightIdRouteImport } from './routes/flight.$id'
import { Route as DestinationSlugRouteImport } from './routes/destination.$slug'
import { Route as DealIdRouteImport } from './routes/deal.$id'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AiConversationIdRouteImport } from './routes/ai.$conversationId'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedCheckoutIdRouteImport } from './routes/_authenticated/checkout.$id'
import { Route as AuthenticatedBookingIdRouteImport } from './routes/_authenticated/booking.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminPermissionsRouteImport } from './routes/_authenticated/admin/permissions'
import { Route as AuthenticatedAdminPackagesRouteImport } from './routes/_authenticated/admin/packages'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin/orders'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminFlightsRouteImport } from './routes/_authenticated/admin/flights'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiIndexRoute = AiIndexRouteImport.update({
  id: '/ai/',
  path: '/ai/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageIdRoute = PackageIdRouteImport.update({
  id: '/package/$id',
  path: '/package/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelIdRoute = HotelIdRouteImport.update({
  id: '/hotel/$id',
  path: '/hotel/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightIdRoute = FlightIdRouteImport.update({
  id: '/flight/$id',
  path: '/flight/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationSlugRoute = DestinationSlugRouteImport.update({
  id: '/destination/$slug',
  path: '/destination/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DealIdRoute = DealIdRouteImport.update({
  id: '/deal/$id',
  path: '/deal/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AiConversationIdRoute = AiConversationIdRouteImport.update({
  id: '/ai/$conversationId',
  path: '/ai/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedCheckoutIdRoute = AuthenticatedCheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingIdRoute = AuthenticatedBookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPermissionsRoute =
  AuthenticatedAdminPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPackagesRoute =
  AuthenticatedAdminPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFlightsRoute =
  AuthenticatedAdminFlightsRouteImport.update({
    id: '/flights',
    path: '/flights',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/flights': typeof FlightsRoute
  '/packages': typeof PackagesRoute
  '/quiz': typeof QuizRoute
  '/result': typeof ResultRoute
  '/support': typeof SupportRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/account': typeof AuthenticatedAccountRoute
  '/ai/$conversationId': typeof AiConversationIdRoute
  '/api/chat': typeof ApiChatRoute
  '/deal/$id': typeof DealIdRoute
  '/destination/$slug': typeof DestinationSlugRoute
  '/flight/$id': typeof FlightIdRoute
  '/hotel/$id': typeof HotelIdRoute
  '/package/$id': typeof PackageIdRoute
  '/ai/': typeof AiIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/flights': typeof AuthenticatedAdminFlightsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/booking/$id': typeof AuthenticatedBookingIdRoute
  '/checkout/$id': typeof AuthenticatedCheckoutIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/flights': typeof FlightsRoute
  '/packages': typeof PackagesRoute
  '/quiz': typeof QuizRoute
  '/result': typeof ResultRoute
  '/support': typeof SupportRoute
  '/account': typeof AuthenticatedAccountRoute
  '/ai/$conversationId': typeof AiConversationIdRoute
  '/api/chat': typeof ApiChatRoute
  '/deal/$id': typeof DealIdRoute
  '/destination/$slug': typeof DestinationSlugRoute
  '/flight/$id': typeof FlightIdRoute
  '/hotel/$id': typeof HotelIdRoute
  '/package/$id': typeof PackageIdRoute
  '/ai': typeof AiIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/flights': typeof AuthenticatedAdminFlightsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/booking/$id': typeof AuthenticatedBookingIdRoute
  '/checkout/$id': typeof AuthenticatedCheckoutIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/flights': typeof FlightsRoute
  '/packages': typeof PackagesRoute
  '/quiz': typeof QuizRoute
  '/result': typeof ResultRoute
  '/support': typeof SupportRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/ai/$conversationId': typeof AiConversationIdRoute
  '/api/chat': typeof ApiChatRoute
  '/deal/$id': typeof DealIdRoute
  '/destination/$slug': typeof DestinationSlugRoute
  '/flight/$id': typeof FlightIdRoute
  '/hotel/$id': typeof HotelIdRoute
  '/package/$id': typeof PackageIdRoute
  '/ai/': typeof AiIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/flights': typeof AuthenticatedAdminFlightsRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/_authenticated/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/booking/$id': typeof AuthenticatedBookingIdRoute
  '/_authenticated/checkout/$id': typeof AuthenticatedCheckoutIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/compare'
    | '/flights'
    | '/packages'
    | '/quiz'
    | '/result'
    | '/support'
    | '/admin'
    | '/account'
    | '/ai/$conversationId'
    | '/api/chat'
    | '/deal/$id'
    | '/destination/$slug'
    | '/flight/$id'
    | '/hotel/$id'
    | '/package/$id'
    | '/ai/'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/flights'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/packages'
    | '/admin/permissions'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/booking/$id'
    | '/checkout/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/compare'
    | '/flights'
    | '/packages'
    | '/quiz'
    | '/result'
    | '/support'
    | '/account'
    | '/ai/$conversationId'
    | '/api/chat'
    | '/deal/$id'
    | '/destination/$slug'
    | '/flight/$id'
    | '/hotel/$id'
    | '/package/$id'
    | '/ai'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/flights'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/packages'
    | '/admin/permissions'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/booking/$id'
    | '/checkout/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/compare'
    | '/flights'
    | '/packages'
    | '/quiz'
    | '/result'
    | '/support'
    | '/_authenticated/admin'
    | '/_authenticated/account'
    | '/ai/$conversationId'
    | '/api/chat'
    | '/deal/$id'
    | '/destination/$slug'
    | '/flight/$id'
    | '/hotel/$id'
    | '/package/$id'
    | '/ai/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/flights'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/packages'
    | '/_authenticated/admin/permissions'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/booking/$id'
    | '/_authenticated/checkout/$id'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRoute
  FlightsRoute: typeof FlightsRoute
  PackagesRoute: typeof PackagesRoute
  QuizRoute: typeof QuizRoute
  ResultRoute: typeof ResultRoute
  SupportRoute: typeof SupportRoute
  AiConversationIdRoute: typeof AiConversationIdRoute
  ApiChatRoute: typeof ApiChatRoute
  DealIdRoute: typeof DealIdRoute
  DestinationSlugRoute: typeof DestinationSlugRoute
  FlightIdRoute: typeof FlightIdRoute
  HotelIdRoute: typeof HotelIdRoute
  PackageIdRoute: typeof PackageIdRoute
  AiIndexRoute: typeof AiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/': {
      id: '/ai/'
      path: '/ai'
      fullPath: '/ai/'
      preLoaderRoute: typeof AiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package/$id': {
      id: '/package/$id'
      path: '/package/$id'
      fullPath: '/package/$id'
      preLoaderRoute: typeof PackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/$id': {
      id: '/hotel/$id'
      path: '/hotel/$id'
      fullPath: '/hotel/$id'
      preLoaderRoute: typeof HotelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flight/$id': {
      id: '/flight/$id'
      path: '/flight/$id'
      fullPath: '/flight/$id'
      preLoaderRoute: typeof FlightIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination/$slug': {
      id: '/destination/$slug'
      path: '/destination/$slug'
      fullPath: '/destination/$slug'
      preLoaderRoute: typeof DestinationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deal/$id': {
      id: '/deal/$id'
      path: '/deal/$id'
      fullPath: '/deal/$id'
      preLoaderRoute: typeof DealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/$conversationId': {
      id: '/ai/$conversationId'
      path: '/ai/$conversationId'
      fullPath: '/ai/$conversationId'
      preLoaderRoute: typeof AiConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/checkout/$id': {
      id: '/_authenticated/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof AuthenticatedCheckoutIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/booking/$id': {
      id: '/_authenticated/booking/$id'
      path: '/booking/$id'
      fullPath: '/booking/$id'
      preLoaderRoute: typeof AuthenticatedBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/permissions': {
      id: '/_authenticated/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthenticatedAdminPermissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/packages': {
      id: '/_authenticated/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AuthenticatedAdminPackagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/flights': {
      id: '/_authenticated/admin/flights'
      path: '/flights'
      fullPath: '/admin/flights'
      preLoaderRoute: typeof AuthenticatedAdminFlightsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminFlightsRoute: typeof AuthenticatedAdminFlightsRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminPackagesRoute: typeof AuthenticatedAdminPackagesRoute
  AuthenticatedAdminPermissionsRoute: typeof AuthenticatedAdminPermissionsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
    AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
    AuthenticatedAdminFlightsRoute: AuthenticatedAdminFlightsRoute,
    AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
    AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
    AuthenticatedAdminPackagesRoute: AuthenticatedAdminPackagesRoute,
    AuthenticatedAdminPermissionsRoute: AuthenticatedAdminPermissionsRoute,
    AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedBookingIdRoute: typeof AuthenticatedBookingIdRoute
  AuthenticatedCheckoutIdRoute: typeof AuthenticatedCheckoutIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedBookingIdRoute: AuthenticatedBookingIdRoute,
  AuthenticatedCheckoutIdRoute: AuthenticatedCheckoutIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRoute,
  FlightsRoute: FlightsRoute,
  PackagesRoute: PackagesRoute,
  QuizRoute: QuizRoute,
  ResultRoute: ResultRoute,
  SupportRoute: SupportRoute,
  AiConversationIdRoute: AiConversationIdRoute,
  ApiChatRoute: ApiChatRoute,
  DealIdRoute: DealIdRoute,
  DestinationSlugRoute: DestinationSlugRoute,
  FlightIdRoute: FlightIdRoute,
  HotelIdRoute: HotelIdRoute,
  PackageIdRoute: PackageIdRoute,
  AiIndexRoute: AiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
