CREATE TABLE public.destinations (
  slug text PRIMARY KEY,
  name text NOT NULL,
  country text NOT NULL,
  country_code text NOT NULL,
  flag text NOT NULL,
  region text NOT NULL,
  tagline text NOT NULL,
  weather text NOT NULL DEFAULT '',
  flight_hours numeric NOT NULL,
  avg_budget_per_person integer NOT NULL,
  matches text[] NOT NULL DEFAULT '{}',
  is_popular boolean NOT NULL DEFAULT false,
  has_offers boolean NOT NULL DEFAULT false,
  hotels jsonb NOT NULL DEFAULT '[]'::jsonb,
  attractions text[] NOT NULL DEFAULT '{}',
  restaurants text[] NOT NULL DEFAULT '{}',
  itinerary text[] NOT NULL DEFAULT '{}',
  sort_order integer NOT NULL DEFAULT 100,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT ON public.destinations TO anon;
GRANT SELECT ON public.destinations TO authenticated;
GRANT ALL ON public.destinations TO service_role;

ALTER TABLE public.destinations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Active destinations are public" ON public.destinations
FOR SELECT TO anon, authenticated USING (is_active);

CREATE INDEX destinations_region_idx ON public.destinations (region, sort_order);

INSERT INTO public.destinations (slug,name,country,country_code,flag,region,tagline,weather,flight_hours,avg_budget_per_person,matches,is_popular,sort_order) VALUES
('santorini','סנטוריני','יוון','GR','🇬🇷','אירופה','האי הלבן-כחול של האגאי, שקיעות מהאגדות וכיפות כחולות.','28° בהיר',3.5,6500,'{beach,romantic,friends}',true,1),
('mykonos','מיקונוס','יוון','GR','🇬🇷','אירופה','חופים, בארים ואווירת קיקלדס תוססת.','29° בהיר',3.5,6800,'{beach,nightlife,friends}',true,2),
('athens','אתונה','יוון','GR','🇬🇷','אירופה','אקרופוליס, שווקים ומטבח יווני מודרני.','30° בהיר',3.5,4200,'{adventure,friends,family}',true,3),
('thessaloniki','סלוניקי','יוון','GR','🇬🇷','אירופה','טיילת ים, קפה איטי וחיי לילה צעירים.','29° בהיר',3,3400,'{friends,nightlife,beach}',true,4),
('rhodes','רודוס','יוון','GR','🇬🇷','אירופה','עיר עתיקה מוקפת חומות וחופים ארוכים.','30° בהיר',2.5,4200,'{beach,family,friends}',true,5),
('crete','כרתים','יוון','GR','🇬🇷','אירופה','האי הגדול ביוון: חופים ורודים, הרים וכפרים.','29° בהיר',3,4600,'{beach,family,nature}',true,6),
('corfu','קורפו','יוון','GR','🇬🇷','אירופה','ירוק, ונציאני ורגוע — הים היוני במיטבו.','28° בהיר',3,4300,'{beach,family,romantic}',false,7),
('zakynthos','זקינתוס','יוון','GR','🇬🇷','אירופה','מפרץ הספינה הטרופה ומים בצבע בלתי אפשרי.','29° בהיר',3.5,4400,'{beach,friends,nature}',false,8),
('kos','קוס','יוון','GR','🇬🇷','אירופה','אופניים, חופים רדודים וכפרים שקטים.','29° בהיר',2.5,3900,'{beach,family}',false,9),
('halkidiki','חלקידיקי','יוון','GR','🇬🇷','אירופה','שלוש אצבעות של יערות אורן וחופים.','28° בהיר',3,4100,'{beach,family,nature}',false,10),
('larnaca','לרנקה','קפריסין','CY','🇨🇾','אירופה','שעת טיסה אחת לים, טיילת ומטבח ים תיכוני.','30° בהיר',1,2900,'{beach,family,friends}',true,11),
('ayia-napa','איה נאפה','קפריסין','CY','🇨🇾','אירופה','בירת חיי הלילה של קפריסין וחופי דגל כחול.','30° בהיר',1,3100,'{beach,nightlife,friends}',true,12),
('paphos','פאפוס','קפריסין','CY','🇨🇾','אירופה','אתרי מורשת עולמית וחופים שקטים.','29° בהיר',1.2,3000,'{beach,family,romantic}',false,13),
('limassol','לימסול','קפריסין','CY','🇨🇾','אירופה','מרינה מודרנית, ספא ומסעדות שף.','30° בהיר',1,3300,'{beach,romantic,nightlife}',false,14),
('rome','רומא','איטליה','IT','🇮🇹','אירופה','קולוסיאום, פסטה ואלפיים שנות היסטוריה.','27° בהיר',4,5200,'{romantic,family,adventure}',true,15),
('milan','מילאנו','איטליה','IT','🇮🇹','אירופה','אופנה, עיצוב ואפריטיבו מושלם.','26° נעים',4.5,5000,'{nightlife,romantic,friends}',true,16),
('venice','ונציה','איטליה','IT','🇮🇹','אירופה','תעלות, גשרים ורומנטיקה בלי מכוניות.','25° נעים',4,5400,'{romantic,family}',false,17),
('florence','פירנצה','איטליה','IT','🇮🇹','אירופה','רנסאנס, יין טוסקני וכיכרות אבן.','27° בהיר',4,5100,'{romantic,nature}',false,18),
('naples','נאפולי','איטליה','IT','🇮🇹','אירופה','פיצה מקורית, וזוב ושער לחוף אמלפי.','28° בהיר',4,4300,'{friends,family,adventure}',false,19),
('amalfi','אמלפי','איטליה','IT','🇮🇹','אירופה','כפרים פסטליים על צוקי הים ולימונים.','27° חמים',4,7500,'{romantic,family,beach}',true,20),
('catania','קטניה','איטליה','IT','🇮🇹','אירופה','סיציליה: אתנה, שווקים וחופים שחורים.','29° בהיר',3.5,4000,'{beach,adventure,family}',false,21),
('sardinia','סרדיניה','איטליה','IT','🇮🇹','אירופה','קוסטה סמרלדה ומים קריביים באירופה.','28° בהיר',4.5,6200,'{beach,romantic,luxury}',false,22),
('barcelona','ברצלונה','ספרד','ES','🇪🇸','אירופה','גאודי, טאפאס וחוף בתוך העיר.','26° נעים',5,4800,'{beach,nightlife,family}',true,23),
('madrid','מדריד','ספרד','ES','🇪🇸','אירופה','מוזיאונים, כדורגל וטאפאס עד הבוקר.','29° בהיר',5.5,4500,'{friends,nightlife,family}',true,24),
('malaga','מלאגה','ספרד','ES','🇪🇸','אירופה','קוסטה דל סול: שמש כל השנה.','28° בהיר',5.5,4200,'{beach,family,friends}',false,25),
('ibiza','איביזה','ספרד','ES','🇪🇸','אירופה','מסיבות אגדיות ומפרצים נסתרים.','28° בהיר',5,6400,'{nightlife,beach,friends}',true,26),
('mallorca','פלמה דה מיורקה','ספרד','ES','🇪🇸','אירופה','מפרצים טורקיז, הרי טרמונטנה ועיר עתיקה.','28° בהיר',5,5000,'{beach,family,nature}',false,27),
('valencia','ולנסיה','ספרד','ES','🇪🇸','אירופה','פאייה מקורית, ארכיטקטורה עתידנית וחוף.','28° בהיר',5,4100,'{beach,family,friends}',false,28),
('tenerife','טנריף','ספרד','ES','🇪🇸','אירופה','הר געש, חופים שחורים ואביב נצחי.','25° נעים',7,5200,'{beach,nature,family}',false,29),
('lisbon','ליסבון','פורטוגל','PT','🇵🇹','אירופה','גבעות, אריחים, פאדו ואוקיינוס.','26° נעים',6,4700,'{romantic,friends,family}',true,30),
('porto','פורטו','פורטוגל','PT','🇵🇹','אירופה','יין פורט, גשרים ורובע היסטורי.','24° נעים',6,4400,'{romantic,friends}',false,31),
('faro','פארו','פורטוגל','PT','🇵🇹','אירופה','אלגרווה: צוקים כתומים וחופי גלישה.','27° בהיר',6.5,4600,'{beach,family,nature}',false,32),
('madeira','מדיירה','פורטוגל','PT','🇵🇹','אירופה','אי פרחים, לבאדות וטרקים בין עננים.','23° נעים',7,5300,'{nature,adventure,romantic}',false,33),
('paris','פריז','צרפת','FR','🇫🇷','אירופה','עיר האורות: מוזיאונים, בראסרי ורומנטיקה.','24° נעים',5,6000,'{romantic,family,luxury}',true,34),
('nice','ניס','צרפת','FR','🇫🇷','אירופה','הריביירה הצרפתית והים הכחול.','27° בהיר',4.5,5600,'{beach,romantic,luxury}',false,35),
('marseille','מרסיי','צרפת','FR','🇫🇷','אירופה','נמל עתיק, קלנקים וטבע ים תיכוני.','28° בהיר',4.5,4600,'{beach,adventure,nature}',false,36),
('lyon','ליון','צרפת','FR','🇫🇷','אירופה','בירת הגסטרונומיה של צרפת.','25° נעים',4.5,4500,'{romantic,friends}',false,37),
('berlin','ברלין','גרמניה','DE','🇩🇪','אירופה','היסטוריה, אמנות רחוב וחיי לילה בלתי נגמרים.','22° נעים',4,4200,'{nightlife,friends,adventure}',true,38),
('munich','מינכן','גרמניה','DE','🇩🇪','אירופה','בירה, גני ביתן ושער לאלפים הבווארים.','23° נעים',4,4400,'{family,friends,nature}',false,39),
('frankfurt','פרנקפורט','גרמניה','DE','🇩🇪','אירופה','קו רקיע מודרני ולב אירופה.','22° נעים',4.5,4000,'{friends,family}',false,40),
('hamburg','המבורג','גרמניה','DE','🇩🇪','אירופה','נמל, תעלות ורובע מוזיקה חי.','20° נעים',4.5,4100,'{friends,nightlife}',false,41),
('vienna','וינה','אוסטריה','AT','🇦🇹','אירופה','ארמונות, קפה ויינר ואופרה.','23° נעים',3.5,4300,'{romantic,family}',true,42),
('salzburg','זלצבורג','אוסטריה','AT','🇦🇹','אירופה','מוצרט, אלפים וטירה מעל העיר.','21° נעים',4,4400,'{family,nature,romantic}',false,43),
('innsbruck','אינסברוק','אוסטריה','AT','🇦🇹','אירופה','סקי ואלפים במרחק הליכה מהעיר.','5° קר',4,5200,'{adventure,nature,family}',false,44),
('zurich','ציריך','שווייץ','CH','🇨🇭','אירופה','אגם, אלפים ורמת חיים גבוהה.','21° נעים',4,7000,'{nature,luxury,family}',false,45),
('geneva','ז''נבה','שווייץ','CH','🇨🇭','אירופה','שער לאלפים ולאגם למאן.','20° נעים',4.5,7200,'{nature,luxury,romantic}',false,46),
('amsterdam','אמסטרדם','הולנד','NL','🇳🇱','אירופה','תעלות, אופניים ומוזיאונים אגדיים.','19° נעים',4.5,4900,'{friends,nightlife,romantic}',true,47),
('brussels','בריסל','בלגיה','BE','🇧🇪','אירופה','שוקולד, וופל ולב אירופה.','19° נעים',4.5,4300,'{family,friends}',false,48),
('prague','פראג','צ''כיה','CZ','🇨🇿','אירופה','עיר אגדות עם גשר קארל ובירה זולה.','21° נעים',3.5,3400,'{friends,romantic,nightlife}',true,49),
('budapest','בודפשט','הונגריה','HU','🇭🇺','אירופה','מרחצאות, רוין ברים ודנובה.','24° נעים',3.5,3200,'{friends,nightlife,romantic}',true,50),
('zagreb','זאגרב','קרואטיה','HR','🇭🇷','אירופה','עיר אוסטרו-הונגרית קטנה ומקסימה.','24° נעים',3,3300,'{friends,family}',false,51),
('split','ספליט','קרואטיה','HR','🇭🇷','אירופה','ארמון דיוקלטיאנוס ושער לאיים.','28° בהיר',3,4200,'{beach,friends,family}',true,52),
('dubrovnik','דוברובניק','קרואטיה','HR','🇭🇷','אירופה','חומות מעל האדריאטי הכחול.','28° בהיר',3,5000,'{romantic,beach,family}',false,53),
('ljubljana','ליובליאנה','סלובניה','SI','🇸🇮','אירופה','עיר ירוקה קטנטנה ליד אגם בלד.','23° נעים',3,3500,'{nature,romantic,family}',false,54),
('tivat','טיוואט','מונטנגרו','ME','🇲🇪','אירופה','מפרץ קוטור, מרינה והרים על הים.','27° בהיר',3,3800,'{beach,nature,luxury}',false,55),
('sofia','סופיה','בולגריה','BG','🇧🇬','אירופה','זולה, קרובה והר ויטושה בגב.','24° נעים',2.5,2600,'{friends,nature,family}',false,56),
('varna','ורנה','בולגריה','BG','🇧🇬','אירופה','חוף הים השחור וטיילת ארוכה.','27° בהיר',2.5,2500,'{beach,family,friends}',true,57),
('bansko','בנסקו','בולגריה','BG','🇧🇬','אירופה','אתר הסקי המשתלם של אירופה.','-2° מושלג',2.5,3200,'{adventure,nature,family}',false,58),
('bucharest','בוקרשט','רומניה','RO','🇷🇴','אירופה','פריז הקטנה של המזרח, במחירי מציאה.','25° נעים',2.5,2600,'{friends,nightlife}',false,59),
('warsaw','ורשה','פולין','PL','🇵🇱','אירופה','עיר שנבנתה מחדש עם היסטוריה עמוקה.','22° נעים',3.5,2900,'{friends,family}',false,60),
('krakow','קרקוב','פולין','PL','🇵🇱','אירופה','כיכר ימי ביניימית ומורשת יהודית.','22° נעים',3.5,2800,'{friends,family}',false,61),
('london','לונדון','בריטניה','GB','🇬🇧','אירופה','מוזיאונים, מחזות זמר ושווקים.','19° משתנה',5,6300,'{family,friends,luxury}',true,62),
('manchester','מנצ''סטר','בריטניה','GB','🇬🇧','אירופה','כדורגל, מוזיקה ותרבות צעירה.','17° משתנה',5.5,5000,'{friends,nightlife}',false,63),
('edinburgh','אדינבורו','בריטניה','GB','🇬🇧','אירופה','טירה על סלע ואווירה סקוטית.','16° משתנה',5.5,5200,'{nature,romantic,adventure}',false,64),
('dublin','דבלין','אירלנד','IE','🇮🇪','אירופה','פאבים, מוזיקה חיה וצוקי מוהר.','17° משתנה',5.5,5100,'{friends,nature,nightlife}',false,65),
('malta','ולטה','מלטה','MT','🇲🇹','אירופה','אבן דבש, מפרצים כחולים והיסטוריה.','28° בהיר',3.5,3900,'{beach,family,adventure}',true,66),
('new-york','ניו יורק','ארצות הברית','US','🇺🇸','צפון אמריקה','העיר שלא ישנה: שדרות, ברודוויי וסנטרל פארק.','21° נעים',12,12000,'{friends,family,nightlife}',true,67),
('miami','מיאמי','ארצות הברית','US','🇺🇸','צפון אמריקה','אושן דרייב, חול לבן ואנרגיה לטינית.','30° בהיר',13,11500,'{beach,nightlife,friends}',true,68),
('los-angeles','לוס אנג''לס','ארצות הברית','US','🇺🇸','צפון אמריקה','הוליווד, חופים ופארקים.','26° בהיר',15,13000,'{beach,family,friends}',false,69),
('las-vegas','לאס וגאס','ארצות הברית','US','🇺🇸','צפון אמריקה','מופעים, קזינו ושער לגרנד קניון.','33° בהיר',15,12500,'{nightlife,friends,adventure}',false,70),
('orlando','אורלנדו','ארצות הברית','US','🇺🇸','צפון אמריקה','בירת פארקי השעשועים העולמית.','31° לח',13,13500,'{family,adventure}',false,71),
('boston','בוסטון','ארצות הברית','US','🇺🇸','צפון אמריקה','אוניברסיטאות, היסטוריה וסתיו צבעוני.','18° נעים',12,11000,'{family,nature}',false,72),
('toronto','טורונטו','קנדה','CA','🇨🇦','צפון אמריקה','עיר רב-תרבותית ושער לניאגרה.','20° נעים',12,11500,'{family,friends,nature}',false,73),
('montreal','מונטריאול','קנדה','CA','🇨🇦','צפון אמריקה','שילוב צרפתי-אמריקאי עם פסטיבלים.','19° נעים',12,11000,'{friends,family,nightlife}',false,74),
('vancouver','ונקובר','קנדה','CA','🇨🇦','צפון אמריקה','הרים, אוקיינוס וטבע פראי.','18° נעים',15,13000,'{nature,adventure,family}',false,75),
('dubai','דובאי','איחוד האמירויות','AE','🇦🇪','המזרח התיכון','יוקרה בלי גבולות, גורדי שחקים ומדבר.','33° בהיר',3.5,8500,'{family,nightlife,friends}',true,76),
('abu-dhabi','אבו דאבי','איחוד האמירויות','AE','🇦🇪','המזרח התיכון','מסגד השיח׳ זאיד, פארקים ואיים.','34° בהיר',3.5,8000,'{family,luxury}',false,77),
('manama','מנאמה','בחריין','BH','🇧🇭','המזרח התיכון','אי קטן עם שווקים, מרינה ומרוצים.','34° בהיר',3.5,6500,'{friends,family}',false,78),
('amman','עמאן','ירדן','JO','🇯🇴','המזרח התיכון','שער לפטרה ולוואדי רם.','30° בהיר',1,2600,'{adventure,nature,family}',false,79),
('aqaba','עקבה','ירדן','JO','🇯🇴','המזרח התיכון','צלילה בים סוף במרחק נסיעה.','33° בהיר',1,2400,'{beach,adventure,family}',false,80),
('sharm','שארם א-שייח''','מצרים','EG','🇪🇬','המזרח התיכון','שוניות אלמוגים והכל כלול על הים.','32° בהיר',1,2500,'{beach,family,friends}',true,81),
('hurghada','חורגדה','מצרים','EG','🇪🇬','המזרח התיכון','ריזורטים על הים האדום וספורט ימי.','32° בהיר',2,2600,'{beach,family,friends}',false,82),
('cairo','קהיר','מצרים','EG','🇪🇬','המזרח התיכון','פירמידות, מוזיאון מצרי ונילוס.','33° בהיר',1.5,3000,'{adventure,family}',false,83),
('marrakesh','מרקש','מרוקו','MA','🇲🇦','אפריקה','ריאדים, שווקים ומדבר בקרבת מקום.','30° בהיר',6,4200,'{adventure,romantic,friends}',true,84),
('casablanca','קזבלנקה','מרוקו','MA','🇲🇦','אפריקה','עיר נמל מודרנית ומסגד חסן השני.','26° נעים',6,4000,'{family,friends}',false,85);

UPDATE public.destinations SET has_offers = true, hotels = h.hotels, attractions = h.attractions, restaurants = h.restaurants, itinerary = h.itinerary
FROM (VALUES
 ('santorini',
  '[{"name":"Cavo Tagoo Santorini","note":"בוטיק עם בריכת אינפיניטי מול הקלדרה"},{"name":"Grace Hotel Auberge","note":"נוף שקיעה מהמפורסמים באי"},{"name":"Astra Suites","note":"סוויטות מדורגות באימרוביגלי"}]'::jsonb,
  ARRAY['שקיעה באויה','חוף אדום','שייט לקלדרה','יקב באי'],
  ARRAY['Ambrosia','Metaxi Mas','Lauda'],
  ARRAY['נחיתה, צ׳ק אין ושקיעה באויה','שייט קלדרה ומעיינות חמים','חופים: אדום, פריסה ופרלייה','טיול יקבים וכפר פירגוס','בוקר חופשי וטיסה חזרה']),
 ('rhodes',
  '[{"name":"Rodos Palace","note":"קלאסיקה עם בריכות גדולות"},{"name":"Sheraton Rhodes Resort","note":"על החוף, מתאים למשפחות"},{"name":"Casa Cook Rhodes","note":"עיצוב בוהו למבוגרים בלבד"}]'::jsonb,
  ARRAY['העיר העתיקה','עמק הפרפרים','לינדוס והאקרופוליס','מפרץ אנתוני קווין'],
  ARRAY['Marco Polo Mansion','Tamam','To Steno'],
  ARRAY['נחיתה וסיור בעיר העתיקה','יום חוף בפליראקי','לינדוס והאקרופוליס','עמק הפרפרים ויקב','קניות וטיסה']),
 ('athens',
  '[{"name":"Electra Metropolis","note":"בריכת גג מול האקרופוליס"},{"name":"Coco-Mat Athens BC","note":"בוטיק שקט ליד המוזיאון"},{"name":"Grande Bretagne","note":"האייקון של כיכר סינטגמה"}]'::jsonb,
  ARRAY['האקרופוליס','מוזיאון האקרופוליס','שוק פסירי','כף סוניון'],
  ARRAY['Ergon House','Nolan','Karamanlidika'],
  ARRAY['נחיתה וסיור בפלאקה','אקרופוליס ומוזיאון','שוק מרכזי וסיור אוכל','טיול יום לכף סוניון','בראנץ׳ וטיסה']),
 ('larnaca',
  '[{"name":"Radisson Blu Larnaca","note":"על הטיילת, מרחק הליכה מהכל"},{"name":"Golden Bay Beach","note":"חוף פרטי ומתאים למשפחות"},{"name":"Lebay Beach Hotel","note":"יחס מחיר-תמורה מצוין"}]'::jsonb,
  ARRAY['טיילת פיניקודס','אגם המלח','כפר לפקרה','צלילה לזנוביה'],
  ARRAY['Militzis','Art Cafe 1900','To Kazani'],
  ARRAY['נחיתה וערב על הטיילת','יום חוף ומנגל ים','כפרי הרים ולפקרה','ספא וקניות','טיסה חזרה']),
 ('rome',
  '[{"name":"Hotel Artemide","note":"מרכזי עם גג פנורמי"},{"name":"Palazzo Naiadi","note":"קלאסי מול כיכר רפובליקה"},{"name":"The First Roma Dolce","note":"בוטיק ליד פיאצה דל פופולו"}]'::jsonb,
  ARRAY['קולוסיאום ופורום','ותיקן וקפלה הסיסטינית','מזרקת טרווי','טרסטוורה'],
  ARRAY['Roscioli','Armando al Pantheon','Da Enzo al 29'],
  ARRAY['נחיתה וטיילת בטרסטוורה','קולוסיאום ופורום רומי','ותיקן ומוזיאונים','וילה בורגזה ושופינג','פסטה אחרונה וטיסה']),
 ('barcelona',
  '[{"name":"H10 Casa Mimosa","note":"ליד קאזה מילא עם בריכת גג"},{"name":"Hotel 1898","note":"על הרמבלה עם ספא"},{"name":"Yurbban Trafalgar","note":"בוטיק שקט ליד העיר העתיקה"}]'::jsonb,
  ARRAY['סגרדה פמיליה','פארק גואל','הרובע הגותי','חוף ברסלונטה'],
  ARRAY['Bar Cañete','Quimet & Quimet','Disfrutar'],
  ARRAY['נחיתה וטאפאס בגותי','סגרדה פמיליה ואייסמפלה','פארק גואל ומונז׳ואיק','יום חוף וברסלונטה','שוק בוקריה וטיסה']),
 ('lisbon',
  '[{"name":"Memmo Alfama","note":"בריכת גג מעל הגגות האדומים"},{"name":"Hotel da Baixa","note":"במרכז, מרחק הליכה מהכל"},{"name":"Bairro Alto Hotel","note":"קלאסיקה מול הנהר"}]'::jsonb,
  ARRAY['אלפמה ופאדו','מנזר ז׳רונימוס','סינטרה','טרם 28'],
  ARRAY['Time Out Market','Cervejaria Ramiro','A Cevicheria'],
  ARRAY['נחיתה וערב פאדו באלפמה','בלם וז׳רונימוס','טיול יום לסינטרה','שוק טיים אאוט וקסקאיש','בראנץ׳ וטיסה']),
 ('paris',
  '[{"name":"Hotel Malte Opera","note":"מרכזי וקלאסי ליד האופרה"},{"name":"Le Pigalle","note":"בוטיק צעיר ברובע 9"},{"name":"Hotel Le Six","note":"שקט במונפרנאס עם ספא"}]'::jsonb,
  ARRAY['מגדל אייפל','לובר','מונמארטר','ורסאי'],
  ARRAY['Bouillon Chartier','Septime','Breizh Café'],
  ARRAY['נחיתה ושייט על הסן','לובר ומרכז העיר','מונמארטר וסאקרה קר','טיול יום לוורסאי','שופינג ומאפים לפני טיסה']),
 ('london',
  '[{"name":"The Z Hotel Piccadilly","note":"קומפקטי ובלב הסוהו"},{"name":"citizenM Tower of London","note":"מודרני עם נוף לטאואר"},{"name":"The Hoxton Shoreditch","note":"אווירה צעירה במזרח לונדון"}]'::jsonb,
  ARRAY['בריטיש מיוזיאום','טאואר ברידג׳','קמדן מרקט','ווסט אנד'],
  ARRAY['Dishoom','Borough Market','Flat Iron'],
  ARRAY['נחיתה וסיור בסוהו','מוזיאונים ובאקינגהאם','קמדן ורייג׳נטס פארק','מחזמר בווסט אנד','שופינג באוקספורד וטיסה']),
 ('prague',
  '[{"name":"Hotel Kings Court","note":"מול המגדל האבקתי"},{"name":"Mosaic House","note":"עיצובי ומשתלם"},{"name":"Augustine","note":"מנזר משופץ במאלה סטראנה"}]'::jsonb,
  ARRAY['גשר קארל','טירת פראג','השעון האסטרונומי','הרובע היהודי'],
  ARRAY['Lokál','Café Savoy','Kantýna'],
  ARRAY['נחיתה וטיול לילי בגשר קארל','טירת פראג ומאלה סטראנה','הרובע היהודי ובירה מקומית','טיול יום לצ׳סקי קרומלוב','שופינג וטיסה']),
 ('amalfi',
  '[{"name":"Hotel Marina Riviera","note":"מרפסות מול הים באמלפי"},{"name":"Villa Franca Positano","note":"בריכת גג מעל פוזיטאנו"},{"name":"Casa Angelina","note":"מינימליסטי עם נוף עוצר נשימה"}]'::jsonb,
  ARRAY['פוזיטאנו','קפרי והגרוטו הכחול','שביל האלים','רוואלו'],
  ARRAY['Da Vincenzo','La Sponda','Il Ritrovo'],
  ARRAY['נחיתה בנאפולי וצ׳ק אין','יום קפרי והגרוטו הכחול','טרק שביל האלים','רוואלו וגני וילה צימברונה','יום חוף ופרידה']),
 ('dubai',
  '[{"name":"Atlantis The Palm","note":"פארק מים ואקווריום"},{"name":"Address Beach Resort","note":"בריכת גג מעל JBR"},{"name":"Rove Downtown","note":"מודרני ומשתלם ליד בורג׳ חליפה"}]'::jsonb,
  ARRAY['בורג׳ חליפה','ספארי מדבר','דובאי מול','פאלם ג׳ומיירה'],
  ARRAY['Zuma','Pierchic','Ravi Restaurant'],
  ARRAY['נחיתה ושקיעה בבורג׳ חליפה','ספארי מדבר וארוחת בדואים','פארק מים באטלנטיס','מרינה, אבּרה ושופינג','בראנץ׳ ופרידה'])
) AS h(slug,hotels,attractions,restaurants,itinerary)
WHERE public.destinations.slug = h.slug;