// Verification contract shared by every provider (demo and live).
//
// Rule: the UI must never render a price or availability that isn't carried by
// a VerifiedQuote. When verification fails the UI shows "מחיר לא זמין" /
// "רענן כדי לאמת זמינות" instead of a stale or invented number.

export type AvailabilityStatus = "available" | "limited" | "sold-out" | "unavailable";

export interface VerifiedQuote {
  /** false => the UI must show the unavailable fallback, not the numbers. */
  verified: boolean;
  perPerson: number | null;
  total: number | null;
  currency: "ILS";
  /** ISO timestamp of the last successful provider verification. */
  verifiedAt: string | null;
  ttlSeconds: number;
  availability: AvailabilityStatus;
  /** Provider-confirmed scarcity only — never generated by the UI. */
  unitsLeft: number | null;
  source: string;
  /** Human-readable reason when verified === false. */
  reason: string | null;
}

export interface BaggageAllowance {
  carryOnIncluded: boolean;
  checkedBagIncluded: boolean;
  checkedBagKg: number | null;
  seatSelectionIncluded: boolean;
  mealIncluded: boolean;
}

export interface FlightSegment {
  airlineCode: string;
  airlineName: string;
  flightNumber: string;
  aircraft: string | null;
  originCode: string;
  originName: string;
  originTerminal: string | null;
  destinationCode: string;
  destinationName: string;
  destinationTerminal: string | null;
  departAt: string;
  arriveAt: string;
  durationMinutes: number;
}

export interface FlightOffer {
  id: string;
  segments: FlightSegment[];
  stops: number;
  /** Minutes on the ground between segments; empty for non-stop. */
  layoverMinutes: number[];
  durationMinutes: number;
  cabin: "economy" | "premium-economy" | "business";
  baggage: BaggageAllowance;
  refundable: boolean;
  fareRules: string[];
  quote: VerifiedQuote;
  source: string;
  deeplink: string | null;
}

export const UNAVAILABLE_PRICE_LABEL = "מחיר לא זמין";
export const REFRESH_TO_VERIFY_LABEL = "רענן כדי לאמת זמינות";

export function isQuoteFresh(q: VerifiedQuote, now = Date.now()): boolean {
  if (!q.verified || !q.verifiedAt) return false;
  return now - new Date(q.verifiedAt).getTime() < q.ttlSeconds * 1000;
}

/** Single place the UI asks "may I render this price?". */
export function canRenderPrice(q: VerifiedQuote | null | undefined): q is VerifiedQuote {
  return Boolean(q && q.verified && q.perPerson !== null && q.availability !== "unavailable");
}

export function unavailableQuote(source: string, reason: string): VerifiedQuote {
  return {
    verified: false,
    perPerson: null,
    total: null,
    currency: "ILS",
    verifiedAt: null,
    ttlSeconds: 0,
    availability: "unavailable",
    unitsLeft: null,
    source,
    reason,
  };
}
